name: Build APKs for release
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HAS_RELEASE_SIGNING: ${{ secrets.KEYSTORE != '' && secrets.KEYSTORE_PROPERTIES != '' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"
          cache: 'gradle'

      - name: Accept SDK licenses
        run: yes | /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Setup signing configs
        if: env.HAS_RELEASE_SIGNING == 'true'
        run: |
          echo "$KEYSTORE" | base64 --decode > test.jks
          echo "$KEYSTORE_PROPERTIES" > keystore.properties
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}

      - name: Get date-time string
        id: datetime
        run: |
          DATE_TAG=$(date +'%Y-%m-%d_%H-%M-%S')
          echo "date_tag=$DATE_TAG" >> $GITHUB_ENV

      - name: Build core release APK
        run: ./gradlew assembleCoreRelease

      - name: Create github release draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || format('build-{0}', env.date_tag) }}
          name: "OuterTune ${{ github.ref_type == 'tag' && github.ref_name || format('build-{0}', env.date_tag) }}"
          draft: false
          body_path: CHANGELOG.md
          files: |
            app/build/outputs/apk/core/release/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.REL_TOKEN || github.token }}
